### ISSUE TITLE
Error when trying to bring up dummy

### ISSUE THREAD

**Issue by jedmunds** [mitchellh/vagrant-aws#103]
Hey, I get this error after the [default] -- Keypair message, I have the correct credentials in my Vagrantfile, here is the output: 

Bringing machine 'default' up with 'aws' provider...
[default] Warning! The AWS provider doesn't support any of the Vagrant
high-level network configurations (`config.vm.network`). They
will be silently ignored.
[default] Launching an instance with the following settings...
[default]  -- Type: m1.small
[default]  -- AMI: ami-7747d01e
[default]  -- Region: us-east-1
[default]  -- Keypair: ec2-keypair
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

undefined method `Errors' for Excon:Module

/home/vagrant/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action/run_instance.rb:91:in `rescue in call'
/home/vagrant/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action/run_instance.rb:61:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
/home/vagrant/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action/warn_networks.rb:14:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
/home/vagrant/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action/sync_folders.rb:21:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/provision.rb:45:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/home/vagrant/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action/connect_aws.rb:41:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/handle_box_url.rb:72:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/machine.rb:147:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/batch_action.rb:63:in`block (2 levels) in run'

**Comment by kenorb** [comment]
Fixed in 5853ebecc0d6d962b556e4da591c0fafb59da908?
