### ISSUE TITLE
Missing required arguments: aws_access_key_id, aws_secret_access_key

### ISSUE THREAD

**Issue by optimuspaul** [mitchellh/vagrant-aws#224]
I'm supplying the access key and the secret key but I get this error:

```
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'stage' machine. Please report this as a bug:

Missing required arguments: aws_access_key_id, aws_secret_access_key

/Users/pjdecoursey/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/core/service.rb:208:in `validate_options'
/Users/pjdecoursey/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/core/service.rb:58:in `new'
/Users/pjdecoursey/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/compute.rb:58:in `new'
/Users/pjdecoursey/.vagrant.d/gems/gems/vagrant-aws-0.4.1/lib/vagrant-aws/action/connect_aws.rb:39:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Users/pjdecoursey/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.7/lib/berkshelf/vagrant/action/configure_chef.rb:23:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Users/pjdecoursey/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.7/lib/berkshelf/vagrant/action/load_shelf.rb:28:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Users/pjdecoursey/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.7/lib/berkshelf/vagrant/action/set_ui.rb:12:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/handle_box_url.rb:30:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in `action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
/Users/pjdecoursey/.vagrant.d/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/Users/pjdecoursey/.vagrant.d/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

Funny thing is it worked five minutes earlier when I brought down the instance. The only change is adding a IAM role to it.

**Comment by jasiedu** [comment]
What policy was role missing?

**Comment by sgarner** [comment]
@optimuspaul I am seeing the same problem after adding a role. How did you fix this?

**Comment by bimp** [comment]
any update on this issue?

**Comment by sergiy17** [comment]
any update?

**Comment by sergiy17** [comment]
For me worked stetting these variables in the 'config/environments/test.rb'
ENV["AWS_ACCESS_KEY_ID"] = "your val"
ENV["AWS_SECRET_ACCESS_KEY"] = "your val"
