### ISSUE TITLE
You cannot disable Availability Zones for ELBs in VPC

### ISSUE THREAD

**Issue by rjocoleman** [mitchellh/vagrant-aws#250]
I'm using the master branch, testing out the ELB feature in a VPC.
ELB feature is hard coded to adjust/disabled the AZs. 'You cannot disable Availability Zones for ELBs in VPC.'

This is some discussion of this here https://github.com/mitchellh/vagrant-aws/pull/88#discussion-diff-6504044

This discussion does not match my experience with ELB, specifically:

> Load balancing between availability zones is made on DNS level. This means that in case
> of ELB configured for 2 availability zones, 50% of traffic goes to the first one and 50% to second.

I'll need to dig into this a little more before I send a PR to resolve it correctly.

Here's the error:

```
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...
==> default: Machine is booted and ready for use!
==> default: Registering i-844994ba at ELB test-vagrant...ok
==> default: Adjusting availability zones of ELB test-vagrant...==> default: Deregistering i-844994ba from ELB test-vagrant...ok
==> default: Adjusting availability zones of ELB test-vagrant...ok
==> default: Terminating the instance...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'chef_solo' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
/Users/rjocoleman/.vagrant.d/gems/gems/excon-0.28.0/lib/excon/middlewares/expects.rb:6:in `response_call': You cannot disable Availability Zones for ELBs in VPC. (Fog::AWS::ELB::ValidationError)
    from /Users/rjocoleman/.vagrant.d/gems/gems/excon-0.28.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/excon-0.28.0/lib/excon/connection.rb:361:in `response'
    from /Users/rjocoleman/.vagrant.d/gems/gems/excon-0.28.0/lib/excon/connection.rb:254:in `request'
    from /Users/rjocoleman/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/xml/sax_parser_connection.rb:36:in `request'
    from /Users/rjocoleman/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/core/deprecated/connection.rb:18:in `request'
    from /Users/rjocoleman/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/aws/elb.rb:187:in `_request'
    from /Users/rjocoleman/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/aws/elb.rb:182:in `request'
    from /Users/rjocoleman/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/aws/requests/elb/disable_availability_zones_for_load_balancer.rb:23:in `disable_availability_zones_for_load_balancer'
    from /Users/rjocoleman/.vagrant.d/gems/gems/fog-1.18.0/lib/fog/aws/models/elb/load_balancer.rb:60:in `disable_availability_zones'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-aws-0.5.0.dev/lib/vagrant-aws/util/elb.rb:44:in `adjust_availability_zones'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-aws-0.5.0.dev/lib/vagrant-aws/util/elb.rb:11:in `register_instance'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-aws-0.5.0.dev/lib/vagrant-aws/action/elb_register_instance.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-aws-0.5.0.dev/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/action/install_chef.rb:38:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/upload.rb:24:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/install.rb:35:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/provision.rb:80:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-aws-0.5.0.dev/lib/vagrant-aws/action/connect_aws.rb:42:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/configure_chef.rb:22:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/load_shelf.rb:27:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/rjocoleman/.vagrant.d/gems/gems/vagrant-berkshelf-2.0.1/lib/berkshelf/vagrant/action/set_ui.rb:11:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box_url.rb:9:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by michaelsharpe** [comment]
Was this ever resolved?  I am currently experiencing the same issue trying to connect a new instance up to a predefined ELB.

**Comment by bgidley** [comment]
I'm getting the same issue - it's 100% reproducible in a non default VPC. When you do a vagrant destroy it fails 

`Adjusting availability zones of ELB web.../var/lib/jenkins/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in response_call': You cannot enable Availability Zones for ELBs in a non default VPC (Fog::AWS::ELB::ValidationError)`

**Comment by bounav** [comment]
It looks like I'm having the same issue trying to provition a VPC instance and add it to an existing ELB.

Double checking the vagrant [README](https://github.com/mitchellh/vagrant-aws) I found the following setting:

> unregister_elb_from_az
> - Removes the ELB from the AZ on removal of the last instance if true (default). In non default VPC this has to be false.

When I don't have the option in my vagrant file (i.e. the option default to _true_) I get the following error when I `vagrant up`: 

```
You cannot enable Availability Zones for ELBs in VPC. (Fog::AWS::ELB::ValidationError)
```

When I add `aws.unregister_elb_from_az = false` to the vagrant file, I then get:

```
You cannot disable Availability Zones for ELBs in VPC. (Fog::AWS::ELB::ValidationError)
```

The only difference between the two error messages is the change from _enable_ to _disable_.

**Comment by raymondjplante** [comment]
Same issue, I've a ELB in a VPC.  Trying to create an instance and attach to ELB and
getting
   
   ==> default: Adjusting availability zones of ELB charlie...==> default: Deregistering i-0f355ab74d88a7f82 from ELB charlie...ok
   ==> default: Terminating the instance...
   /my/home/.vagrant.d/gems/2.2.5/gems/excon-0.55.0/lib/excon/middlewares/expects.rb:7:in  `response_call': You cannot disable Availability Zones for ELBs in VPC. (Fog::AWS::ELB::ValidationError)
      
Here's my settings:

    aws.ami = "some-ami"
    aws.instance_type = "t2.micro"
    aws.region = "us-east-1"
    aws.subnet_id = "a-subnet-in-vpc"
    aws.security_groups = ['some-securitygroup']
    aws.elb = "an-elb-in-vpc"
    
    aws.associate_public_ip = true
    aws.unregister_elb_from_az = false
    aws.ssh_host_attribute = :public_ip_address
