### ISSUE TITLE
"Undefined method `destroy`" for node 

### ISSUE THREAD

**Issue by jayjanssen** [mitchellh/vagrant-aws#265]
I'm trying to destroy all running nodes in my environment, but I get an error on a node that isn't created:

```
 vagrant status
Current machine states:

team1node1                not created (aws)
team1node2                running (aws)
team1node3                running (aws)
team1test                 running (aws)
team2node1                not created (aws)
team2node2                not created (aws)
team2node3                running (aws)
team2test                 running (aws)
team3node1                not created (aws)
team3node2                running (aws)
team3node3                not created (aws)
team3test                 running (aws)
team4node1                not created (aws)
team4node2                running (aws)
team4node3                not created (aws)
team4test                 running (aws)
team5node1                not created (aws)
team5node2                running (aws)
team5node3                running (aws)
team5test                 running (aws)
team6node1                not created (aws)
team6node2                not created (aws)
team6node3                not created (aws)
team6test                 running (aws)
team7node1                not created (aws)
team7node2                running (aws)
team7node3                not created (aws)
team7test                 not created (aws)
team8node1                not created (aws)
team8node2                running (aws)
team8node3                not created (aws)
team8test                 running (aws)
team9node1                not created (aws)
team9node2                not created (aws)
team9node3                running (aws)
team9test                 running (aws)
team10node1               not created (aws)
team10node2               running (aws)
team10node3               not created (aws)
team10test                not created (aws)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

```
$ vagrant destroy -f
==> team10test: Terminating the instance...
/Users/jayj/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/terminate_instance.rb:26:in `call': undefined method `destroy' for nil:NilClass (NoMethodError)
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jayj/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/elb_deregister_instance.rb:19:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jayj/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/connect_aws.rb:42:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jayj/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/action/update_all.rb:27:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/commands/destroy/command.rb:30:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/cli.rb:42:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:252:in `cli'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.3/bin/vagrant:166:in `<main>'
```

```
$ vagrant plugin list
vagrant-aws (0.5.0)
vagrant-hostmanager (1.5.0)
vagrant-login (1.0.1, system)
vagrant-share (1.1.0, system)
vagrant-vmware-fusion (2.4.1)
```

**Comment by ColinHebert** [comment]
This issue should be closed
