### ISSUE TITLE
Unable to vagrant up --provider=aws from Jenkins shell

### ISSUE THREAD

**Issue by Baaleos** [mitchellh/vagrant-aws#278]
Executing the following from Jenkins hosted on a 
Ubuntu Server 14.04 LTS (PV)   64bit
(My Vagrant is the latest deb package from the official website, and the plugin was installed via vagrant plugin install vagrant-aws 
Had some trouble getting the pre-reqs installed - but in the end the install completed)

cd ${WORKSPACE}
who
echo ${USER}
vagrant up --provider=aws

With the following output

[JonnyTest] $ /bin/sh -xe /tmp/hudson332574242727980688.sh
- cd /var/lib/jenkins/workspace/JonnyTest
- who
  ubuntu   pts/0        2014-08-06 08:21 (80.76.207.49)
- echo root
  root
- vagrant up --provider=aws
  The provider 'aws' could not be found, but was requested to
  back the machine 'default'. Please use a provider that exists.
  Build step 'Execute shell' marked build as failure
  Recording test results
  Publishing Javadoc
  Finished: FAILURE

When I am in the same directory ( /var/lib/jenkins/workspace/JonnyTest )
and I execute vagrant up --provider=aws

I get this

==> default: HandleBoxUrl middleware is deprecated. Use HandleBox instead.
==> default: This is a bug with the provider. Please contact the creator
==> default: of the provider you use to fix this.
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Launching an instance with the following settings...
==> default:  -- Type: t1.micro
==> default:  -- AMI: ami-384d8450
==> default:  -- Region: us-east-1
==> default:  -- Keypair: NWNUbuntu
==> default:  -- Security Groups: ["NWN_Ubuntu"]
==> default:  -- Block Device Mapping: []
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: false
==> default:  -- Assigning a public IP address in a VPC: false
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:259:in `initialize': Permission denied - /var/lib/jenkins/workspace/JonnyTest/.vagrant/machines/default/aws/id (Errno::EACCES)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:259:in`open'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:259:in `open'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:259:in`id='
        from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/run_instance.rb:122:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/sync_folders.rb:23:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in`busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/connect_aws.rb:42:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box.rb:56:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box_url.rb:9:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in`block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in`run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in`block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/batch_action.rb:82:in`block (2 levels) in run'

If I execute sudo vagrant up --provider=aws

ubuntu@ip-10-180-232-33:/var/lib/jenkins/workspace/JonnyTest$ sudo vagrant up --provider=aws
Bringing machine 'default' up with 'aws' provider...
==> default: HandleBoxUrl middleware is deprecated. Use HandleBox instead.
==> default: This is a bug with the provider. Please contact the creator
==> default: of the provider you use to fix this.
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Launching an instance with the following settings...
==> default:  -- Type: t1.micro
==> default:  -- AMI: ami-384d8450
==> default:  -- Region: us-east-1
==> default:  -- Keypair: NWNUbuntu
==> default:  -- Security Groups: ["NWN_Ubuntu"]
==> default:  -- Block Device Mapping: []
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: false
==> default:  -- Assigning a public IP address in a VPC: false
==> default: Waiting for instance to become "ready"...

The instance eventually becomes ready.

I've downloaded the dummy aws box via the box add dummy <url>
When I do vagrant box list from ssh or jenkins it does list dummy with aws as a provider

I've also tried

cd ${WORKSPACE}
who
echo ${USER}
vagrant box add default https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box --force
vagrant box list
vagrant up --provider=aws

cd ${WORKSPACE}
who
echo ${USER}
vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box --force
vagrant box list
vagrant up dummy --provider=aws

and the output just keeps saying negative things :-\

[JonnyTest] $ /bin/sh -xe /tmp/hudson5964755880903405188.sh
- cd /var/lib/jenkins/workspace/JonnyTest
- who
  ubuntu   pts/0        2014-08-06 08:21 (80.76.207.49)
- echo root
  root
- vagrant box add default https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box --force
  ==> box: Adding box 'default' (v0) for provider: 
  box: Downloading: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

[K    box: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[K==> box: Successfully added box 'default' (v0) for 'aws'!
- vagrant box list
  default (aws, 0)
  dummy   (aws, 0)
- vagrant up --provider=aws
  The provider 'aws' could not be found, but was requested to
  back the machine 'default'. Please use a provider that exists.
  Build step 'Execute shell' marked build as failure
  Recording test results
  Publishing Javadoc
  Finished: FAILURE

Anyone ever manage to get vagrant to work when invoked via Jenkins?

I've set my Jenkins instance to be running as root, so permissions shouldnt be an issue?

I've also tried putting these commands into a sh file, and executing from jenkins, but it then has difficulty cd'ing to directories.

HELP!!

**Comment by kenorb** [comment]
You can probably close yourself.
