### ISSUE TITLE
elastic ip address allocation isn't working

### ISSUE THREAD

**Issue by mmroden** [mitchellh/vagrant-aws#310]
I set the following in my vagrant file:

```
 aws.elastic_ip = "<my IP>"  # a known, existing, non-occupied elastic IP
```

but that results in the following error message:
    VagrantPlugins::AWS::Errors::FogError: There was an error talking to AWS. The error message is shown
   below:

```
Could not allocate Elastic IP.
```

Assuming that there might be some string strangeness going on, I removed the quotes (either double or single) and produced:

```
There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/Users/mroden/Documents/src/more-like-this-pipeline/Vagrantfile:47: no .<digit> floating literal anymore; put 0 before dot
   aws.elastic_ip = xx.xx.xx.xx  # actual number redacted
                       ^
/Users/mroden/Documents/src/more-like-this-pipeline/Vagrantfile:47: syntax error, unexpected tFLOAT, expecting '('
```

I think there must be something wrong with run_instance.sh, line 202.  My ruby-fu isn't that strong, but it looks like that if statement will produce a zero if the regex is matched, according to http://www.ruby-doc.org/core-2.1.4/Regexp.html.  Maybe change to 

```
if /\d+\.\d+\.\d+\.\d+/.match(elastic_ip)
```

or even better, something like

```
IPAddress.valid?(elastic_IP)
```

since the regex would allow for an IP like 235.34242.1242.53 to pass.

**Comment by woodcoder** [comment]
Works for me in 0.6.0 too, where the IP is allocated (but not associated) in the AWS console.
```
    aws.elastic_ip = "1.2.3.4"
```

**Comment by mercer** [comment]
I also confirm that in 0.6.0 vagrant-aws up now correctly associates an unused given elastic ip and vagrant destroy releases it.

However, if the given elastic ip is already in use, a new ip will be reserved and associated on vagrant up. Vagrant destroy will fail, and you'll have to cleanup manually (terminate instance, release "spawned" elastic ip).

Perhaps vagrant up should fail if given elastic ip is already in use. Should I open an issue with this? 

```
vagrant destroy -f
/root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/expects.rb:6:in `response_call': InvalidParameterValue => You must specify an allocation id when releasing a VPC elastic IP address (Fog::Compute::AWS::Error)
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:365:in `response'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:235:in `request'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/idempotent.rb:22:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:255:in `rescue in request'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:203:in `request'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/idempotent.rb:22:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:255:in `rescue in request'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:203:in `request'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/idempotent.rb:22:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/middlewares/base.rb:10:in `error_call'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:255:in `rescue in request'
	from /root/.vagrant.d/gems/gems/excon-0.41.0/lib/excon/connection.rb:203:in `request'
	from /root/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
	from /root/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
	from /root/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/compute.rb:522:in `_request'
	from /root/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/compute.rb:517:in `request'
	from /root/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/requests/compute/release_address.rb:25:in `release_address'
	from /root/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/terminate_instance.rb:41:in `release_address'
	from /root/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/terminate_instance.rb:20:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/elb_deregister_instance.rb:19:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/connect_aws.rb:42:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/destroy/command.rb:30:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

**Comment by jimafisk** [comment]
Quick thing worth mentioning is that AWS places default limits on things like Elastic IPs, so if you've reached your limit you will get this error: "There was an error talking to AWS. The error message is shown below: Could not allocate Elastic IP." My account originally had a limit of 5, but you can request an increase via your EC2 console under "Limits" in the left sidebar.

**Comment by kenorb** [comment]
This happened to my as well:

```
==> mt-aws-foo: Waiting for instance to become "ready"...
==> mt-aws-foo: Terminating the instance...
There was an error talking to AWS. The error message is shown
below:

Could not allocate Elastic IP.
```

Vagrant 1.8.1 with vagrant-aws (0.7.0) and the following [`Vagrantfile`](https://github.com/EA31337/FX-MT-VM/blob/d07f64a18c2fab4b2562c9bc83413acdf3cb3526/Vagrantfile).

I've `aws.elastic_ip` set to `true` and 0 running instances on my EC2.
