### ISSUE TITLE
SSL Unable to verify certificate vagrant 1.7.0

### ISSUE THREAD

**Issue by scriminaci** [mitchellh/vagrant-aws#327]
Hi,

since I updated vagrant to the 1.7.0 version I get this error. The problem is not present with vagrant 1.6.5

```
vagrant status
/home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/ssl_socket.rb:121:in `connect_nonblock': Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure). (Excon::Errors::SocketError)
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/ssl_socket.rb:121:in `block in initialize'
    from /home/opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/ssl_socket.rb:117:in `initialize'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:380:in `new'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:380:in `socket'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:105:in `request_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/mock.rb:47:in `request_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:15:in `request_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:232:in `request'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/idempotent.rb:26:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:255:in `rescue in request'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:203:in `request'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/idempotent.rb:26:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:255:in `rescue in request'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:203:in `request'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/idempotent.rb:26:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:255:in `rescue in request'
    from /home/mario/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:203:in `request'
    from /home/mario/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
    from /home/mario/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
    from /home/mario/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/compute.rb:522:in `_request'
    from /home/mario/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/compute.rb:517:in `request'
    from /home/mario/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/requests/compute/describe_instances.rb:71:in `describe_instances'
    from /home/mario/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/models/compute/servers.rb:63:in `all'
    from /home/mario/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/aws/models/compute/servers.rb:150:in `get'
    from /home/mario/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/read_state.rb:24:in `read_state'
    from /home/mario/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/read_state.rb:15:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
    from /home/mario/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/action/connect_aws.rb:42:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builder.rb:116:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `block in run'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/util/busy.rb:19:in `busy'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `run'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:212:in `action_raw'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:189:in `block in action'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:516:in `lock'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:176:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:176:in `action'
    from /home/mario/.vagrant.d/gems/gems/vagrant-aws-0.5.0/lib/vagrant-aws/provider.rb:32:in `state'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:478:in `state'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:141:in `initialize'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/vagrantfile.rb:75:in `new'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/vagrantfile.rb:75:in `machine'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:614:in `machine'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:201:in `call'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:200:in `map'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:200:in `with_target_vms'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/plugins/commands/status/command.rb:20:in `execute'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:42:in `execute'
    from /home/opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:301:in `cli'
    from /home/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.0/bin/vagrant:174:in `<main>'
```

My environment is:
Ubuntu 14.10
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
rvm 1.26.4 (stable) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

vagrant plugin list
vagrant-aws (0.5.0)
vagrant-hostmanager (1.5.0)
vagrant-login (1.0.1, system)
vagrant-share (1.1.3, system)

Regards,
Mario

**Comment by sdodson** [comment]
This is should be fixed  fixed in 1.7.2

https://github.com/mitchellh/vagrant/issues/5001

**Comment by frankbb** [comment]
I just tested this and i confirm that this bug is not happening anymore with Vagrant 1.7.2.
