### ISSUE TITLE
creating instance in classic ec2 fails with error security group does not exist

### ISSUE THREAD

**Issue by gnandiga** [mitchellh/vagrant-aws#345]
I am trying to start a classic-ec2 machine instead of using a VPC subnet, and it fails with error **The security group 'sg-f........' does not exist (Fog::Compute::AWS::NotFound)**

I have tried to bring the same machine with a security group id in a vpc and that works fine, but in classic-ec2 I get this error.

Here is the full error from *vagrant up node*
```
Bringing machine 'node' up with 'aws' provider...
==> node: Warning! The AWS provider doesn't support any of the Vagrant
==> node: high-level network configurations (`config.vm.network`). They
==> node: will be silently ignored.
==> node: Launching an instance with the following settings...
==> node:  -- Type: m1.medium
==> node:  -- AMI: ami-.....
==> node:  -- Region: us-west-2
==> node:  -- Keypair: key
==> node:  -- Security Groups: ["sg-f......."]
==> node:  -- Block Device Mapping: []
==> node:  -- Terminate On Shutdown: false
==> node:  -- Monitoring: false
==> node:  -- EBS optimized: false
==> node:  -- Assigning a public IP address in a VPC: false
==> node: Warning! Vagrant might not be able to SSH into the instance.
==> node: Please check your security groups settings.
/Users/[user]/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/expects.rb:6:in `response_call': The security group 'sg-f.......' does not exist (Fog::Compute::AWS::NotFound)
  from /Users/[user]/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/middlewares/response_parser.rb:8:in `response_call'
  from /Users/[user]/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:365:in `response'
  from /Users/[user]/.vagrant.d/gems/gems/excon-0.42.1/lib/excon/connection.rb:235:in `request'
  from /Users/[user]/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
  from /Users/[user]/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
  from /Users/[user]/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/compute.rb:522:in `_request'
  from /Users/[user]/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/compute.rb:517:in `request'
  from /Users/[user]/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/requests/compute/run_instances.rb:139:in `run_instances'
  from /Users/[user]/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/models/compute/servers.rb:159:in `save_many'
  from /Users/[user]/.vagrant.d/gems/gems/fog-1.26.0/lib/fog/aws/models/compute/server.rb:201:in `save'
  from /Users/[user]/.vagrant.d/gems/gems/fog-core-1.27.2/lib/fog/core/collection.rb:50:in `create'
  from /Users/[user]/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:102:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/[user]/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/[user]/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/call.rb:53:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/[user]/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:212:in `action_raw'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:189:in `block in action'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:516:in `lock'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `action'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run
```

Any pointers to solve this is greatly appreciated.

**Comment by gnandiga** [comment]
Found the solution,  when starting instance in  classic-ec2 I need to use the **group name**, when using the VPC I need to use the **group id**.
