### ISSUE TITLE
synced-folders type is not working properly

### ISSUE THREAD

**Issue by betolink** [mitchellh/vagrant-aws#357]
When I ran into [bug#340](https://github.com/mitchellh/vagrant-aws/issues/340) I changed my Vagrantfile to use rsync instead of nfs for the default override.vm.synced_ folder.

```
congif.vm.synced_folder ".", "/vagrant",type: "rsync"
```

However I still got the "No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug." and my debug stack said:

```
DEBUG host: Searching for cap: nfs_installed
DEBUG host: Checking in: linux
DEBUG host: Found cap: nfs_installed in linux
 INFO host: Execute capability: nfs_installed [#<Vagrant::Environment: ~/project>] (linux)
 INFO synced_folders: Synced Folder Implementation: rsync
 INFO synced_folders:   - /tmp/vagrant-puppet-4/manifests: ~/project/manifests => /tmp/vagrant-puppet-4/manifests
 INFO synced_folders: Synced Folder Implementation: nfs
 INFO synced_folders:   - /vagrant: . => /vagrant
 INFO synced_folders: Invoking synced folder prepare for: rsync
 INFO synced_folders: Invoking synced folder prepare for: nfs
 INFO synced_folders: Invoking synced folder enable: nfs
ERROR warden: Error occurred: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::AWS::Action::RunInstance:0x000000031c5a40>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::NFSNoHostIP: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.>
ERROR vagrant: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/synced_folders/nfs/synced_folder.rb:43:in `enable'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:90:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:87:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/home/scm/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/disks/scm/home/scm/.vagrant.d/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/disks/scm/home/scm/.vagrant.d/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/disks/scm/home/scm/.vagrant.d/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
 INFO interface: Machine: error-exit ["Vagrant::Errors::NFSNoHostIP", "No host IP was given to the Vagrant core NFS helper. This is\nan internal error that should be reported as a bug."]
Build step 'Execute shell' marked build as failure
```

I still don't get why NFS is being invoked since supposedly I specified rsync for the default folder.

Vagrant 1.6.5
vagrant-aws 0.6.0

**Comment by patricecaron** [comment]
Same problem.... 

...
....
==> default: Machine is booted and ready for use!
No host IP was given to the Vagrant core NFS helper. This is an internal error that should be reported as a bug.

**Comment by mbainter** [comment]
If you're only using AWS, you can work around this by disabling nfs like so:
```
config.nfs.functional = false
```
