### ISSUE TITLE
uninitialized constant VagrantPlugins::AWS::Action::HandleBox

### ISSUE THREAD

**Issue by mcorsen** [mitchellh/vagrant-aws#359]
When trying to bring up a box I get the following error.
$ vagrant up master --provider=aws
Bringing machine 'master' up with 'aws' provider...
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'master' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/home/matt.olsen/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/home/matt.olsen/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/home/matt.olsen/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/home/matt.olsen/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'

$ vagrant --version
Vagrant 1.4.3

**Comment by sebaes** [comment]
Hi, same here, this is the "debug" output if it helps
Vagrant 1.4.3 on Ubuntu 14.04 LTS


$ vagrant up --provider=aws --debug

 INFO global: Vagrant version: 1.4.3
 INFO global: Ruby version: 1.9.3
 INFO global: RubyGems version: 1.8.23
 INFO global: VAGRANT_HOME="/links/virtual_machines"
 INFO global: VAGRANT_LOG="debug"
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: RedHat guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/opensuse/plugin.rb
 INFO manager: Registered plugin: OpenSUSE host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
 INFO vagrant: `vagrant` invoked: ["up", "--provider=aws", "--debug"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x000000020c9b10>)
 INFO environment:   - cwd: /mnt/sda7/virtual_machines/salt_test_aws
 INFO environment: Home path: /links/virtual_machines
 INFO environment: Local data path: /mnt/sda7/virtual_machines/salt_test_aws/.vagrant
DEBUG environment: Creating: /mnt/sda7/virtual_machines/salt_test_aws/.vagrant
DEBUG environment: Loading plugins from: /links/virtual_machines/plugins.json
 INFO environment: Loading plugin from JSON: vagrant-aws
 INFO manager: Registered plugin: AWS
 INFO manager: Registered required plugin: vagrant-aws
 INFO root: Loaded plugin vagrant-aws, version 0.6.0
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002530fc8>
 INFO environment: Running hook: environment_load
 INFO environment: Initializing config...
 INFO loader: Set :default = "/usr/share/vagrant/config/default.rb"
DEBUG loader: Populating proc cache for "/usr/share/vagrant/config/default.rb"
DEBUG loader: Load procs for pathname: /usr/share/vagrant/config/default.rb
 INFO loader: Set :home = #<Pathname:/links/virtual_machines/Vagrantfile>
DEBUG loader: Populating proc cache for #<Pathname:/links/virtual_machines/Vagrantfile>
DEBUG loader: Load procs for pathname: /links/virtual_machines/Vagrantfile
 INFO loader: Set :root = #<Pathname:/mnt/sda7/virtual_machines/salt_test_aws/Vagrantfile>
DEBUG loader: Populating proc cache for #<Pathname:/mnt/sda7/virtual_machines/salt_test_aws/Vagrantfile>
DEBUG loader: Load procs for pathname: /mnt/sda7/virtual_machines/salt_test_aws/Vagrantfile
 INFO loader: Loading configuration in order: [:default, :home, :root]
DEBUG loader: Loading from: default (evaluating)
DEBUG loader: Loading from: home (evaluating)
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG hosts: Host path search classes: [VagrantPlugins::HostFreeBSD::Host, VagrantPlugins::HostGentoo::Host, VagrantPlugins::HostOpenSUSE::Host, VagrantPlugins::HostRedHat::Host, VagrantPlugins::HostSlackware::Host, VagrantPlugins::HostArch::Host, VagrantPlugins::HostWindows::Host, VagrantPlugins::HostLinux::Host, VagrantPlugins::HostBSD::Host]
 INFO hosts: Host class: VagrantPlugins::HostLinux::Host
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000000214c970>
 INFO cli: CLI: [] "up" ["--provider=aws", "--"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command ["--provider=aws", "--"]
DEBUG command: 'Up' each target VM...
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: []
DEBUG command:  -- options: {:provider=>"aws"}
DEBUG command: Loading all machines...
 INFO environment: Getting machine: default (aws)
 INFO environment: Uncached load of machine.
 INFO loader: Set :vm_default = []
 INFO loader: Loading configuration in order: [:default, :home, :root, :vm_default]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: home (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
 INFO box_collection: Searching for box: dummy (aws) in /links/virtual_machines/boxes/dummy/aws/metadata.json
 INFO box_collection: Box found: dummy (aws)
 INFO environment: Applying 2 provider overrides. Reloading config.
 INFO loader: Set :vm_default_dummy_aws = [["2", #<Proc:0x000000023658d8>], ["2", #<Proc:0x000000023696e0>]]
DEBUG loader: Populating proc cache for ["2", #<Proc:0x000000023658d8>]
DEBUG loader: Populating proc cache for ["2", #<Proc:0x000000023696e0>]
 INFO loader: Loading configuration in order: [:default, nil, :home, :root, :vm_default, :vm_default_dummy_aws]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: home (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: vm_default_dummy_aws (evaluating)
DEBUG loader: Loading from: vm_default_dummy_aws (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: VagrantPlugins::AWS::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x00000002498bd8>
 INFO machine:   - Data dir: /mnt/sda7/virtual_machines/salt_test_aws/.vagrant/machines/default/aws
 INFO command: With machine: default (AWS (new))
 INFO interface: info: Bringing machine 'default' up with 'aws' provider...
Bringing machine 'default' up with 'aws' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Batch action will parallelize: true
 INFO batch_action: Starting action: #<Vagrant::Machine:0x000000023cd6e0> up {:destroy_on_error=>true, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil, :provider=>"aws"}
 INFO machine: Calling action: up on provider AWS (new)
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000000251e580>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::BatchMultiError: An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/mnt/sda7/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'>
ERROR vagrant: An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/mnt/sda7/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'
ERROR vagrant: /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:109:in `run'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:213:in `block (2 levels) in batch'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:208:in `tap'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:208:in `block in batch'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:207:in `batch'
/usr/share/vagrant/plugins/commands/up/command.rb:55:in `execute'
/usr/lib/ruby/vendor_ruby/vagrant/cli.rb:38:in `execute'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:484:in `cli'
/usr/bin/vagrant:127:in `<main>'
 INFO interface: error: An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/mnt/sda7/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/links/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/mnt/sda7/virtual_machines/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'

**Comment by mcorsen** [comment]
Downloading and installing the latest version of Vagrant (1.7.2) from vagrantup.com fixed this issue for me. I had installed Vagrant using apt-get on Ubuntu 14.04.

**Comment by gidantribal** [comment]
same problem here....with vagrant 1.6.4

**Comment by gidantribal** [comment]
For a quick fix (still, oh god why everything stops working :/... please thank you the author):
http://blog.damore.it/2015/01/aws-vagrant-no-host-ip-was-given-to.html
