### ISSUE TITLE
The executable 'powershell' Vagrant is trying to run was not found in the %PATH% variable

### ISSUE THREAD

**Issue by bl4design** [mitchellh/vagrant-aws#363]
I'm working with Vagrant 1.7.2 and having issues trying to boot a vagrant instance using (Gitbash): 
`vagrant up --provider=aws`

I get the error  _"The executable 'powershell' Vagrant is trying to run was not found in the %PATH% variable"_

Vagrant boots just fine when running (gitbash): 
`vagrant up `

I have uninstalled and re-installed vagrant and still receive the error. Im on a windows 8.1 machine and running this command from Gitbash. Although, when I run the same command with the AWS plugin in windows command prompt I get the error:

_"The box you're attempting to add doesn't support the provider you requested..."_

I have referred to issue [issue 3674 - The executable 'bsdtar' Vagrant is trying to run was not found in the %PATH% variable] (https://github.com/mitchellh/vagrant/issues/3674) and have upgraded from vagrant 1.6.5 to 1.7.2 thinking there was an issue with 1.6.5 - considering the release notes for 1.7.2. mention a [bug fix to a powershell component] (communicators/winrm: detect parse errors in PowerShell and error). I maybe interpreting this change element, if so my bad. 

Can anyone point me in the right direction or lend any possible solutions? Thanks!!

**Comment by yanivrefael** [comment]
I have the same problem

**Comment by otravers** [comment]
For the record I ran into this issue (with a local Vagrant, not using AWS) with a new box set up to use SMB for synced folders on a Windows 8.1 host with a CentOS guest. When I changed sync_type to "default" I was able to proceed with vagrant up. So using SMB looks to be triggering this issue.

**Comment by houami** [comment]
still getting the same error.
any fix for this please?

**Comment by bharadwajpro** [comment]
Same issue here. Any one here to help?

**Comment by jschonme** [comment]
I had this problem when running `vagrant up` from a Cygwin Terminal using zsh.

I got Vagrant 1.9.7 to work by appending the path to powershell.exe to my PATH.  In .zshrc:

        PATH="${PATH}:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0"

**Comment by sk-1987** [comment]
Thanks a ton Jschonme

**Comment by goginenisri** [comment]
The executable 'powershell' Vagrant is trying to run was not
found in the %PATH% variable.  plz slove

**Comment by hemantcrv** [comment]
thanks John Schönmeier

**Comment by bharadwajpro** [comment]
@jschonme This solves the issue

**Comment by MhdHajjo** [comment]
what worked with me its to add into the "Path" which is in the Environment Variables the path of the powershell "C:\Windows\System32\WindowsPowerShell\v1.0".

Dont forget to rerun the "Git Bash" or whatever command line tool you use because it caching the system variables

**Comment by SachinMore** [comment]
@MhadHajjo: so do you mean to add PowerShell path into Environment Variables; and then GitBash will work perfectly for this, right!. As I am getting this attached error.
![untitled](https://user-images.githubusercontent.com/15128443/38197914-1aa28eb4-36a8-11e8-9c7f-b7e2c33b0b00.png)

**Comment by MhdHajjo** [comment]
@SachinMore you should find the variable called "Path" which contains the system variables and add to it the variable to your P
![variables](https://user-images.githubusercontent.com/36037661/38202103-e198abec-369a-11e8-8fac-e001eef56805.PNG)
owerShell 

![syspowershell](https://user-images.githubusercontent.com/36037661/38202112-e7ef9050-369a-11e8-9e03-46459103bd6a.PNG)

this could be the problem in your case because the operating system variables should be able to recognize the command "vagrant" and execute it correctly

**Comment by apurvageete** [comment]
@MhdHajjo you are asking me to add path with ev..??? can u plz explain again

**Comment by XedinUnknown** [comment]
Run your shell as administrator.

**Comment by adrianorosaferreira** [comment]
Thanks a lot, @MhdHajjo, this solved here.

**Comment by AhmadFox** [comment]
thank you @MhdHajjo it's working

**Comment by jesus143** [comment]
This works for me https://github.com/mitchellh/vagrant-aws/issues/363#issuecomment-315194696
answer  from @jschonme 

Thank you!

**Comment by AkhilRedddy** [comment]
can any one help me on this
![screenshot 41](https://user-images.githubusercontent.com/37811669/50066476-0df66900-01e2-11e9-8e80-f797f74997ac.png)

**Comment by MhdHajjo** [comment]
@AkhilRedddy

-  first of all be sure that you had installed Vagrant,
- then be sure that the vagrant parameter is configured correctly in the _Enviroment parameters 
 >>system variables >> path_ 
![image](https://user-images.githubusercontent.com/36037661/50084131-3b4d1200-01f6-11e9-811a-343620155494.png)

please close and reopen the command line after the enviroment parameter confiuration because it loads them once its open

**Comment by AkhilRedddy** [comment]
Hi Mitchellh,

I've configured the vagrant parameter correctly in the Environment
parameters still I'm facing same problem.

can you help me on this ?

**Comment by AkhilRedddy** [comment]
I've configured and facing same error .
![screenshot 4](https://user-images.githubusercontent.com/37811669/52130905-81085180-2661-11e9-84eb-e8c84c31b290.png)

**Comment by MhdHajjo** [comment]
> I've configured and facing same error .
> ![screenshot 4](https://user-images.githubusercontent.com/37811669/52130905-81085180-2661-11e9-84eb-e8c84c31b290.png)

please be sure to rerun your command prompt tool and also as an administrator

**Comment by AkhilRedddy** [comment]
![screenshot 5](https://user-images.githubusercontent.com/37811669/52131730-82d31480-2663-11e9-86e8-4c896c76d36d.png)

**Comment by MhdHajjo** [comment]
it failed not because it didn't find the Vagrant, but because you giving unknown provider!, normally the provider will be configured in the vagrantFile in the related path ( do you have a vagrant configuration in the path C:\Users\sari\akhil) ?
in general, it sounds you have right vagrant environment but you run it incorrectly

**Comment by AkhilRedddy** [comment]
can you guide how to connect vagrant using Virtualbox ?

**Comment by mrbardia72** [comment]
from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:72:in `<module:Win32>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:4:in `<top (required)>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:7:in `<top (required)>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:172:in `<class:Hosts>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:169:in `<class:Resolv>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:39:in `<top (required)>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/action/network.rb:
top (required)>'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/action.rb:77:in `b
 action_boot'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/action.rb:62:in `t

 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/action.rb:62:in `a
oot'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/action.rb:344:in `
4 levels) in action_start'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:47:in `call'

 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23
ll'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in f
_action'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in r

 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'

 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23
ll'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in f
_action'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in r

 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'

 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
 from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23

**Comment by IceTony** [comment]
export PATH=$PATH:/mnt/c/Windows/System32/WindowsPowerShell/v1.0

**Comment by antoinebou12** [comment]
PC: WSL ubuntu 18.04
Windows 10 with installed vagrant 2.2.7 and virtualbox 6.1
```bash
curl -O https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
sudo apt install ./vagrant_2.2.7_x86_64.deb
export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"
export PATH="$PATH:/mnt/c/Windows/System32/WindowsPowerShell/v1.0"
export PATH="$PATH:/mnt/c/WINDOWS/system32"
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"

```

Also put your project in the /mnt/c/ directory
https://www.vagrantup.com/docs/other/wsl.html

**Comment by gotomuneeb** [comment]
> what worked with me its to add into the "Path" which is in the Environment Variables the path of the powershell `C:\Windows\System32\WindowsPowerShell\v1.0`
> 
> Dont forget to rerun the "Git Bash" or whatever command line tool you use because it caching the system variables

Thanks Its working now

**Comment by rvangala936** [comment]
Any solution to this problem?

I have "C:\WINDOWS\System32\WindowsPowerShell\v1.0\" in the System PATH environment.
I also added the above to PATH using export and ran vagrant. Still get the below error:

rXXX@DESKTOP-XYZ:/mnt/c$ sudo vagrant up
Vagrant failed to initialize at a very early stage:

Failed to locate the powershell executable on the available PATH. Please
ensure powershell is installed and available on the local PATH, then
run the command again.
++++

**Comment by lsy0566** [comment]
This problem is not solution...

**Comment by andreasgeorgiou** [comment]
> @AkhilRedddy
> 
> * first of all be sure that you had installed Vagrant,
> * then be sure that the vagrant parameter is configured correctly in the _Enviroment parameters
> 
> > > system variables >> path_
> > > ![image](https://user-images.githubusercontent.com/36037661/50084131-3b4d1200-01f6-11e9-811a-343620155494.png)
> 
> please close and reopen the command line after the enviroment parameter confiuration because it loads them once its open

Thanks friend.

**Comment by rogatzkij** [comment]
I solved same error just creating same link to `powershell.exe` with name `powershell`

```bash
rogatzkij@FX505DT:~$ which powershell.exe
/mnt/c/Windows/System32/WindowsPowerShell/v1.0//powershell.exe
rogatzkij@FX505DT:~$ sudo ln -s /mnt/c/Windows/System32/WindowsPowerShell/v1.0//powershell.exe /usr/bin/powershell
```

**Comment by MohammedShakeeb112** [comment]
Need help got similar error ` 'cmd.exe'`

`$ vagrant init ubuntu/bionic64`
On windows10
Error message:
`Vagrant failed to initialize at a very early stage:
The executable 'cmd.exe' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.
`
Thanks in Advance

**Comment by MohammedShakeeb112** [comment]
@MhdHajjo 
added the vagrant variable into path even though having the same issue as mentioned in the previous post 

![Untitled](https://user-images.githubusercontent.com/96920879/148637198-d7d825ee-367e-4e6d-ac93-6f32faaa9aaa.png)

**Comment by MohammedShakeeb112** [comment]
> what worked with me its to add into the "Path" which is in the Environment Variables the path of the powershell `C:\Windows\System32\WindowsPowerShell\v1.0`
> 
> Dont forget to rerun the "Git Bash" or whatever command line tool you use because it caching the system variables

@MhdHajjo 
Thanks it worked for me
