### ISSUE TITLE
AuthFailure => AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by michal-jobseeker** [mitchellh/vagrant-aws#372]
Env: MacOsX 10.10.2
Ruby: 2.1.5
Vagrant: 1.7.2
vagrant-aws: 0.6.0

vagrant up --provider=aws
```
An unexpected error occurred when executing the action on the
<my machine> machine. Please report this as a bug:

AuthFailure => AWS was not able to validate the provided access credentials

/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/expects.rb:6:in `response_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:372:in `response'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:236:in `request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/compute.rb:528:in `_request'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/compute.rb:523:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/requests/compute/describe_security_groups.rb:38:in `describe_security_groups'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/models/compute/security_groups.rb:64:in `all'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:192:in `block in allows_ssh_port?'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:191:in `map'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:191:in `allows_ssh_port?'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:98:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by IyadKandalaft** [comment]
That sounds like a bad username and access key. Check your was credentials
and try again.

**Comment by michal-jobseeker** [comment]
Yeah, the creds are correct. And not switched (key with secret)

**Comment by howardzhang** [comment]
I encountered the same issue. 
Env: Ubuntu 12.04
Ruby: 1.9.3p0
Vagrant: 1.7.2
vagrant-aws: 0.6.0

**Comment by jimafisk** [comment]
I was having the same problem on my Ubuntu 14.04.2 LTS laptop. I noticed my computer's clock was wrong, even though it was set to update "automatically from the internet." Running the following fixed my computer's clock and resolved my connection issues to AWS:

sudo ntpdate ntp.ubuntu.com

**Comment by howardzhang** [comment]
@jimafisk if your PC's clock was wrong, such as the time of the PC is more than an hour to now, the error I got is "Request has expired." This is a totally different problem.

**Comment by andreijs** [comment]
@jimafisk yeah that was the issue, if the time is wrong by more than a few minutes like 5 it will not work

**Comment by andreijs** [comment]
and the issue vagrant actually reports is fairly confusing

**Comment by montenegromax** [comment]
I'm with same problem.
My credentials are correct.
I've checked the clock and username and access key... ok!
Please, someone solved the problem?

Env: Ubuntu 12.04 | Debian Wheezy
Ruby: 2.2.1p85
Vagrant: 1.7.2
vagrant-aws: 0.6.0

**Comment by joshbaldock** [comment]
I too am having this issue. I have checked my clock and access key and secret.
vagrant status - works fine, no connection issues to AWS.
vagrant up - fails with the "AuthFailure => AWS was not able to validate the provided access credentials" error.

Please let me know what further information you need that may assist with troubleshooting.

**Comment by joshbaldock** [comment]
Turns out this was an issue with the file format of my sourced bash file containing the environment variables. Which caused the ID and SECRET variables to have invisible trailing whitespace which caused issues with the AWS authentication.

Fixing the file format on the bash sourced file and reloading the environment variables, fixed my issue.

**Comment by BardiaAfshin** [comment]
I'm having issue setting up the dummy demo outlined in README.md

here's my ruby Vagrant script
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "asdf"
    aws.secret_access_key = "asdf"

    aws.region = "us-east-1"

    aws.ami = "ami-7747d01e"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/me/.ssh/id_rsa"
  end
end
```
I get the following error, look at the last line.

```error
○ → vagrant up --provider=aws
Bringing machine 'default' up with 'aws' provider...
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Warning! You didn't specify a keypair to launch your instance with.
==> default: This can sometimes result in not being able to access your instance.
==> default: Launching an instance with the following settings...
==> default:  -- Type: m3.medium
==> default:  -- AMI: ami-7747d01e
==> default:  -- Region: us-east-1
==> default:  -- Block Device Mapping: []
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: false
==> default:  -- Assigning a public IP address in a VPC: false
There was an error talking to AWS. The error message is shown
below:

AuthFailure => AWS was not able to validate the provided access credentials
```

**Comment by brijs** [comment]
@BardiaAfshin, are you missing `aws.keypair_name` ? Also, make sure the keypair was created for the same region as specified in the `Vagrantfile`.

**Comment by sakovias** [comment]
I was having this issue when my keys stopped working for some reason. You can check if your keys work with this Python script:
``` python
#!/bin/env python
import boto.ec2

conn = boto.ec2.connect_to_region('us-west-2', aws_access_key_id=key_id, aws_secret_access_key=key)
regions = conn.get_all_regions()
print(regions)
```

**Comment by amr-atef-afifi** [comment]
For me I had the same error "AWS was not able to validate the provided access credentials", the problem was as @jimafisk metioned, my computer's clock was wrong I used his provided command and it passed this issue.

**Comment by BardiaAfshin** [comment]
I've ran ntupdate on my box, this issue persists.

**Comment by amr-atef-afifi** [comment]
If your AWS credentials are saved in ~/.boto file, use the following convention for saving the credentials it's more safe since boto checks for credentials in that path first
~/.aws/credentials

And write your profile as following
[default]
...
[test]
...

**Comment by MosesMunene** [comment]
Updating the time fixed it for me. Thank you.

**Comment by sandeep19** [comment]
Correcting the system time got this fixed.

**Comment by sabrehagen** [comment]
system time skeq was my problem too. `sudo ntpdate pool.ntp.org` fixed it for me.

**Comment by blues-man** [comment]
yes ntp enabled and running resolved also for me

**Comment by ephracis** [comment]
Having the same issue. Time is correct. It works in awscli and from @sakovias python snippet. But when running `vagrant up --provider=aws` I get the following:

> AuthFailure => AWS was not able to validate the provided access credentials

Running Vagrant 1.8.1 and aws-cli 1.10.35 on OS X 10.11.5

**Comment by ramsrib** [comment]
I'm also facing this same issue.
>> : AuthFailure => AWS was not able to validate the provided access credentials (Fog::Compute::AWS::Error)

exporting AWS_SESSION_TOKEN fixes the issue.  Not sure, whether its needed or not.

**Comment by dduffyha** [comment]
I had this issue and it resolved when I renewed my aws-credential-client because I had short lived creds.

**Comment by MiguelAngel82** [comment]
Hi all!

I've had the same problem and I've solved as @jimafisk shown in this [comment](https://github.com/mitchellh/vagrant-aws/issues/372#issuecomment-87429450).

I've checked the time of my machine, executing `date` command, and I've realized that the time was behind as comparing with an "official" time (for example https://time.is/es/). So I've executed the command `sudo ntpdate ntp.ubuntu.com` and everything works as expected.

Thanks a lot!

Regards,
Miguel.

**Comment by danielrive** [comment]
hello
i had the same problem, i configure the time and date with correct zone

**Comment by danielrive** [comment]
hello
i had the same problem, i configure the time and date with correct zone
i have Linux debian S.O

**Comment by fertobar** [comment]
👍  @danielrive . After I set the time in OSX worked like a charm again

**Comment by krisvishwanathan** [comment]
This is very common problem, I keep getting this errors all of sudden working from terminal. All that I needed to make sure is to set correct time on the local machine. For some reason clock its out of sync. Goto google search for UTC time. Then on your local machine type "Date" you will fine time difference. Set to correct time using date +%T -s "11:14:00". You should be all set.

**Comment by jjones40** [comment]
I know this is an older thread. But I had this problem, and the fix was (very) simply removing any spaces between my KEY variables, the equals sign, and the Key values.

**Comment by sallar** [comment]
I had the same issue on Mac and it turned out my corporate computer was using a corporate time service which was a couple of minutes behind. Changed it to apple time service and it fixed the issue.

**Comment by rathinikunj** [comment]
Correcting the system time got it fixed. 

Although below command sometimes does not update the time if ntpd is already running. 
` sudo ntpdate pool.ntp.org `

Follow the below steps
` sudo service ntp stop`
` sudo ntpdate pool.ntp.org`
` sudo service ntp start`

Thanks to @jimafisk

**Comment by selhorn** [comment]
For what it's worth, I was having this issue (AWS was not able to validate the provided access credentials) and I stumbled on this page when looking for help. 

It turned out there were two sets of credentials stored on my box: one under c:\.aws\ and one under c:\users\myname\.aws\. Once I fixed both, I was fine.

Details: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence

**Comment by Usamaliaquat123** [comment]
Check that the server clock is synchronized.
If the clock is delayed, can cause this error:
`AWS was not able to validate the provided access credentials`

**Comment by hdryx** [comment]
I confirm also that `sudo ntpdate pool.ntp.org `solved the issue in Fedora 30

**Comment by gawbul** [comment]
I had the same issue on Ubuntu 18.04. I had to do the following:

```
sudo apt-get install -y ntp
sudo service ntp stop
sudo ntpd -gq
sudo service ntp start
```

**NB:** This is the preferred method of updating the system time on Ubuntu, as `ntpdate` is deprecated.

**Comment by universal-architect** [comment]
sudo ntpdate pool.ntp.org solved for me

**Comment by thejazzid** [comment]
check this one. worked for me https://aws.amazon.com/premiumsupport/knowledge-center/iam-validate-access-credentials/

**Comment by kevocrowley** [comment]
This caught me out when calling the boto library from an earlier version of ansible

You need to use a different env variable name for the session token, run this after you export your keys from aws programatically 
AWS_SECURITY_TOKEN="${AWS_SESSION_TOKEN}"

**Comment by sandervanburken** [comment]
It also won't work if creds come from an exported `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` *but* an empty `AWS_SESSION_TOKEN` is also set. To resolve do: `unset AWS_SESSION_TOKEN`.

**Comment by HARSHAL732001** [comment]
My system's time is properly syncing with actual time and also my `aws_access_key` and `aws_secret_key` are correct.
Then also facing the issue of 
`AuthFailure : AWS was not able to validate the provided access credentials`
`ResponseError404`
