### ISSUE TITLE
ami not found

### ISSUE THREAD

**Issue by dav92lee** [mitchellh/vagrant-aws#402]
I get this error each time i run `vagrant up`:

`middlewares/expects.rb:6:in 'response_call': The image id '[ami-e7527ed7]' does not exist (Fog::Compute::AWS::NotFound)`

Was wondering if I am doing something wrong in terms of listing the ami I want to use.  `ami-e7527ed7` is a default ami provided by amazon, so should be findable...

My vagrant file is the following:

>Vagrant.configure("2") do |config|
>  config.vm.box = "dummy"
>
>  config.vm.provider :aws do |aws, override|
>    aws.access_key_id = "KEYIDHERE"
>    aws.secret_access_key = "SECRETKEYHERE"
>    aws.ami = "ami-e7527ed7"
>
>
>    region = "us-west-2b"
>    override.ssh.username = "root"
>  end
>end

**Comment by DanielCaldwell** [comment]
I had this same issue. I had to switch my region to "us-west-2" rather than "us-west-2a". Hope this helps.

**Comment by kenorb** [comment]
The same here:

```
==> mt-test:  -- VPC tenancy specification: default
~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/middlewares/expects.rb:6:in `response_call': The image id '[ami-9abea4fb]' does not exist (Fog::Compute::AWS::NotFound)
	from ~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from ~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/connection.rb:389:in `response'
	from ~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/connection.rb:253:in `request'
	from ~/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
	from ~/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
	from ~/.vagrant.d/gems/gems/fog-aws-0.9.2/lib/fog/aws/compute.rb:525:in `_request'
	from ~/.vagrant.d/gems/gems/fog-aws-0.9.2/lib/fog/aws/compute.rb:520:in `request'
	from ~/.vagrant.d/gems/gems/fog-aws-0.9.2/lib/fog/aws/requests/compute/run_instances.rb:139:in `run_instances'
```

Just changed:

    aws.ami = "ami-fce3c696"
    aws.region = "us-east-1"

to:

    aws.ami = 'ami-9abea4fb'
    aws.region = 'us-west-2'

**Comment by pcragone** [comment]
It's been a while, but any update on how to fix this issue?
