### ISSUE TITLE
Reduce the number of DescribeInstances calls

### ISSUE THREAD

**Issue by WyseNynja** [mitchellh/vagrant-aws#403]
We've got a lot of engineers using vagrant and vagrant-aws and are having issues with Request limits:

```
==> VAGRANTNAME: Waiting for instance to become "ready"...
==> VAGRANTNAME: Waiting for SSH to become available...
==> VAGRANTNAME: Terminating the instance...
==> VAGRANTNAME: Running cleanup tasks for 'shell' provisioner...
==> VAGRANTNAME: Running cleanup tasks for 'shell' provisioner...
==> VAGRANTNAME: Running cleanup tasks for 'file' provisioner...
==> VAGRANTNAME: Running cleanup tasks for 'shell' provisioner...
/tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:6:in `response_call': RequestLimitExceeded => Request limit exceeded. (Fog::Compute::AWS::Error)
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:372:in `response'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:236:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-aws-0.6.0/lib/fog/aws/compute.rb:527:in `_request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-aws-0.6.0/lib/fog/aws/compute.rb:522:in `request'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-aws-0.6.0/lib/fog/aws/requests/compute/describe_instances.rb:81:in `describe_instances'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-aws-0.6.0/lib/fog/aws/models/compute/servers.rb:62:in `all'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/fog-aws-0.6.0/lib/fog/aws/models/compute/servers.rb:149:in `get'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/read_ssh_info.rb:24:in `read_ssh_info'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/read_ssh_info.rb:15:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:485:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:24:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:407:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/communicators/ssh/communicator.rb:319:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/communicators/ssh/communicator.rb:125:in `ready?'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:161:in `block in call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/util/timer.rb:9:in `time'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:155:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /tmp/lifeguardnPAaTX/cddeaab0-90cf-4d1a-8b67-cb8add0c0389/gems/gems/vagrant-triggers-0.5.0/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

I'm going to get everyone using Vagrant 1.7.4 to make sure this hasn't been fixed there, but I don't think it has since we see a lot of DescribeInstance calls from the latest version and I'm pretty sure everyone is on the latest vagrant-aws, too.

**Comment by WyseNynja** [comment]
Confirmed that we are using vagrant-aws 0.6.0 everywhere even if we are using differing versions of vagrant.

**Comment by yshemesh** [comment]
It happens to us too with Vagrant 1.7.4 and vagrant-aws 0.6.0.
It appears to happen when vagrant is trying to SSH into the AWS Instance.

# vagrant plugin list
vagrant-aws (0.6.0)
vagrant-share (1.1.4, system)
# vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4

**Comment by lawrenceong** [comment]
From what I can see in the code, exponential backoff is not yet implemented.  This is what's required to fix it once and for all.  Of course, reducing the number of describe calls would help too, but it is not the final solution.

**Comment by VVMichaelSawyer** [comment]
Pull request open for the fog-aws gem: fog/fog-aws#361
