### ISSUE TITLE
intermittent error when trying to provision/ssh EC2 boxes

### ISSUE THREAD

**Issue by troyshu** [mitchellh/vagrant-aws#406]
Any idea what might be causing the following intermittent error when trying to ssh into or provision an EC2 box (popped up a day or two ago)? Something to do with the excon and/or fog gems? Sometimes the commands work fine, sometimes the error is thrown.

Thanks

```
/Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/expects.rb:6:in `response_call': Expected(200) <=> Actual(0 Unknown) (Excon::Errors::HTTPStatusError)
excon.error.response
  :body          => "[a long amazon response]"
  :headers       => {
    "Content-Type" => "text/xml;charset=UTF-8"
    "Date"         => "Wed, 12 Aug 2015 22:52:38 GMT"
    "Server"       => "AmazonEC2"
    "Vary"         => "Accept-Encoding"
  }
  :local_address => "192.168.1.216"
  :local_port    => 63241
  :reason_phrase => "K"
  :remote_ip     => "[some ip]"
  :status        => 0
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:372:in `response'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:236:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/troyshu/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/compute.rb:528:in `_request'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/compute.rb:523:in `request'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/requests/compute/describe_instances.rb:81:in `describe_instances'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/models/compute/servers.rb:63:in `all'
	from /Users/troyshu/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/models/compute/servers.rb:150:in `get'
	from /Users/troyshu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/read_ssh_info.rb:24:in `read_ssh_info'
	from /Users/troyshu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/read_ssh_info.rb:15:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/troyshu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /Users/troyshu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:24:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:415:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/ssh_exec.rb:26:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:174:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:174:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/ssh/command.rb:59:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/ssh/command.rb:41:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by troyshu** [comment]
doesn't seem to be happening any more... maybe Amazon fixed something on their side

**Comment by troyshu** [comment]
Sorry, this seems to be happening again. A few days ago, provisioning and ssh was working perfectly fine... Any ideas?

**Comment by xtinagodwin** [comment]
I am also having the problem. I have been using knife ec2 server create to successfully provision EC2s for a long time, and it randomly stopped working in us-east-1 last week. Others I've found online seem to be having the same problem. I think the problem is on Amazon's side and I just created a support ticket.

@troyshu are you using us-east-1?

**Comment by daanemanz** [comment]
@xtinagodwin @troyshu same issue here when using [fog](https://github.com/fog/fog), seems to be related to something wonky in us-east-1. Are you using IAM?

**Comment by xtinagodwin** [comment]
@daanemanz yes I am using IAM

**Comment by daanemanz** [comment]
I'm opening a ticket with AWS to investigate -- it seems to be an issue related to the metadata service.

Approximate times of errors:
* Aug 11 16:00 UTC - Aug 13 1:00 UTC
* Aug 14 12:30 UTC - present

**Comment by daanemanz** [comment]
Update -- this seems to be related to the **excon** gem. @troyshu I see that whatever version of vagrant-aws you're using, uses **excon-0.44.4** which is very likely due to the use of an older version of **fog** (version 1.22, see [here](https://github.com/mitchellh/vagrant-aws/blob/master/vagrant-aws.gemspec#L18)).

This issue was fixed in https://github.com/excon/excon/pull/494. After updating the **excon** gem, I indeed started getting the expected result.

**Comment by xtinagodwin** [comment]
@daanemanz This fixed the problem for me as well! Thanks!!!

**Comment by davidjh** [comment]
Thank you - updating to excon-0.45.4 fixed the issue for me too.

**Comment by buren** [comment]
Thanks @daanemanz! https://github.com/mitchellh/vagrant-aws/issues/406#issuecomment-131919977

**Comment by troyshu** [comment]
I actually did not touch my gems, and the error stopped appearing about a week or so; things are now working consistently. Maybe Amazon did something on their side. Will close this for now...
