### ISSUE TITLE
Failures when using Windows 2012 AMI

### ISSUE THREAD

**Issue by tal5ab** [mitchellh/vagrant-aws#414]
I have a working vagrantfile with some simple cookbooks that is working well on a 2008 R2 AMI
When moving to a 2012 AMI i am getting two issues
1 - when running vagrant up , vagrant fail to find the installed chef client and tries to install it:

if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 54.209.156.44
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
 INFO winrm: WinRM not up: #<VagrantPlugins::CommunicatorWinRM::Errors::ConnectionTimeout: Vagrant t
imed out while attempting to connect via WinRM. This usually
means that the VM booted, but there are issues with the WinRM configuration
or network connectivity issues. Please try to `vagrant reload` or
`vagrant up` again.>
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: aws
 INFO machine: Calling action: read_ssh_info on provider AWS (i-a27d0b76)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #Vagrant::Action::Builder:0x72aa3a0
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x72a8a98
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x72a8a80
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x72cb370
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x72cb370
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x72a8a80
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x72a8a98
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 54.209.156.44
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
 INFO winrm: WinRM not up: #<VagrantPlugins::CommunicatorWinRM::Errors::ConnectionTimeout: Vagrant t
imed out while attempting to connect via WinRM. This usually
means that the VM booted, but there are issues with the WinRM configuration
or network connectivity issues. Please try to `vagrant reload` or
`vagrant up` again.>
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: aws
 INFO machine: Calling action: read_ssh_info on provider AWS (i-a27d0b76)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #Vagrant::Action::Builder:0x38c5800
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x38df498
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x38df450
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x3a01868
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x3a01868
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x38df450
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x38df498
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 54.209.156.44
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
DEBUG winrmshell: Output: {:data=>[{:stdout=>"WIN-6MD54DC99PQ"}, {:stdout=>"\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
 INFO run_instance: Time for SSH ready: 282.2720000743866
 INFO interface: info: Machine is booted and ready for use!
 INFO interface: info: ==> default: Machine is booted and ready for use!
==> default: Machine is booted and ready for use!
 INFO warden: Calling IN action: #<Proc:0x4dde9b8@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x4dde9b8@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1
.7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::RunInstance:0x4db0b78
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ElbRegisterInstance:0x4d8a958
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::WarnNetworks:0x4d8a970
 INFO synced_folders: Invoking synced folder enable: winrm
 INFO interface: info: Uploading with WinRM: C:/DevOps/test_AWS/cookbooks => C:/vagrant-chef/327e1ec
ded8ecdfe0d60a92260d5b12d/cookbooks
 INFO interface: info: ==> default: Uploading with WinRM: C:/DevOps/test_AWS/cookbooks => C:/vagrant
-chef/327e1ecded8ecdfe0d60a92260d5b12d/cookbooks
==> default: Uploading with WinRM: C:/DevOps/test_AWS/cookbooks => C:/vagrant-chef/327e1ecded8ecdfe0
d60a92260d5b12d/cookbooks
DEBUG winrm: Attempting WinRM upload attempt number 1
 INFO winrm: Uploading: C:/DevOps/test_AWS/cookbooks to C:/vagrant-chef/327e1ecded8ecdfe0d60a92260d5
b12d/cookbooks
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::SyncedFolders:0x4d4e070
 INFO provision: Writing provisioning sentinel so we don't provision again
 INFO interface: info: Running provisioner: chef_solo...
 INFO interface: info: ==> default: Running provisioner: chef_solo...
==> default: Running provisioner: chef_solo...
 INFO environment: Running hook: provisioner_run
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: provisioner_run #<Method: Vagrant::Action::Builtin::Provision#run_prov
isioner>
 INFO warden: Calling IN action: #<Proc:0x37bcbe8@C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.
7.4/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO chef_solo: Checking for Chef installation...
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: aws
 INFO machine: Calling action: read_ssh_info on provider AWS (i-a27d0b76)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #Vagrant::Action::Builder:0x394d5b0
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x396ec70
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x396ebc8
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x3a30fc8
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x3a30fc8
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x396ebc8
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x396ec70
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 54.209.156.44
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
DEBUG winrmshell: Output: {:data=>[{:stdout=>"WIN-6MD54DC99PQ"}, {:stdout=>"\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
DEBUG guest: Searching for cap: chef_installed
DEBUG guest: Checking in: windows
DEBUG guest: Found cap: chef_installed in windows
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: aws
 INFO machine: Calling action: read_ssh_info on provider AWS (i-a27d0b76)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #Vagrant::Action::Builder:0x4ec3900
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x4ec1f68
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x4ec1f50
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x4f0a040
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x4f0a040
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x4ec1f50
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x4ec1f68
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 54.209.156.44
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
DEBUG winrmshell: Output: {:data=>[{:stdout=>"WIN-6MD54DC99PQ"}, {:stdout=>"\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
DEBUG guest: Searching for cap: chef_installed
DEBUG guest: Checking in: windows
DEBUG guest: Found cap: chef_installed in windows
 INFO guest: Execute capability: chef_installed [#<Vagrant::Machine: default (VagrantPlugins::AWS::P
rovider)>, :latest](windows)
DEBUG winrmshell: powershell executing:
if ((&knife --version) -Match "Chef: *"){ exit 0 } else { exit 1 }
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
DEBUG winrmshell: Output: {:data=>[{:stderr=>"#< CLIXML\r\n"}, {:stderr=>"<Objs Version=\"1.1.0.1\"
xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">&amp; : The term 'knife' is
 not recognized as the name of a cmdlet, function, _x000D__x000A_</S><S S=\"Error\">script file, or
operable program. Check the spelling o"}, {:stderr=>"f the name, or if a path _x000D__x000A_</S><S S
=\"Error\">was included, verify that the path is correct and try again._x000D__x000A_</S><S S=\"Erro
r\">At line:1 char:7_x000D__x000A_</S><S S=\"Error\">\+ if ((&amp;knife --version) -Match \"Chef: *\"
){ exit 0 } else { exit 1 }_x000D__x000A_</S><S S=\"Error\">\+       ~~~~~_x000D__x000A_</S><S S=\"Er
ror\">    + CategoryInfo          : ObjectNotFound: (knife:String) [], CommandNotFou _x000D__x000A_<
/S><S S=\"Error\">   ndException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : Comma
ndNotFoundException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>"}], :exitcode=>1}
 INFO interface: detail: Installing Chef (latest)...
 INFO interface: detail:     default: Installing Chef (latest)...
    default: Installing Chef (latest)...
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: aws
 INFO machine: Calling action: read_ssh_info on provider AWS (i-a27d0b76)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_ssh_info #Vagrant::Action::Builder:0x38ae538
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::ConfigValidate:0x38c4f48
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ConnectAWS:0x38c4f00
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling IN action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x39d17f0
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ReadSSHInfo:0x39d17f0
 INFO warden: Calling OUT action: #VagrantPlugins::AWS::Action::ConnectAWS:0x38c4f00
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x38c4f48
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 54.209.156.44
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: plaintext
DEBUG winrmshell: Output: {:data=>[{:stdout=>"WIN-6MD54DC99PQ"}, {:stdout=>"\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
DEBUG guest: Searching for cap: chef_install
DEBUG guest: Checking in: windows
ERROR warden: Error occurred: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #VagrantPlugins::AWS::Action::RunInstance:0x4db0b78
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x4b3ec28
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-08d0caea4973d67024aa1df2ecf9e1de
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #Vagrant::Action::Builder:0x4e77ee0
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::GuestCapabilityNotFound: Vagrant attempted to execute the capabili
ty 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.>
ERROR vagrant: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
ERROR vagrant: C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/guest.rb:45:in `res
cue in capability'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/guest.rb:43:in`capability'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/chef/installer.rb:31:in `
ensure_installed'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/chef/provisioner/base.rb:
34:in`install_chef'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/chef/provisioner/chef_sol
o.rb:45:in `provision'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:133:in
`run_provisioner'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in`block in f
inalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in`block in r
un'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in`run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:121:in
`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:121:in
 `block in call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:103:in
`each'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:103:in
 `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in f
inalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in r
un'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in`busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in`call
'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/Vagrant/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:
25:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in
`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in`call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in r
un'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in`busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in`action_raw'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action
'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in`lock'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in`action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 le
vels) in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in`call
'
C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `bloc
k in create_with_logging_context'
 INFO interface: error: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
 INFO interface: Machine: error-exit ["Vagrant::Errors::GuestCapabilityNotFound", "Vagrant attempted
 to execute the capability 'chef_install'\non the detect guest OS 'windows', but the guest doesn't\n
support that capability. This capability is required for your\nconfiguration of Vagrant. Please eith
er reconfigure Vagrant to\navoid this capability or fix the issue by creating the capability."]

2 - When i try to run provision only it fails for an issue with vagrant-elevated-shell.ps1 :
C:\DevOps\test_AWS>vagrant provision
==> default: Uploading with WinRM: C:/DevOps/test_AWS/cookbooks => C:/vagrant-chef/327e1ecded8ecdfe0
d60a92260d5b12d/cookbooks
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: Exception calling "Run" with "1" argument(s): "Element not found. (Exception
==> default: from HRESULT: 0x80070490)"
==> default: At C:\tmp\vagrant-elevated-shell.ps1:61 char:1
==> default: + $registered_task.Run($null) | Out-Null
==> default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> default:
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

I looked into this error , and i found out that the scheduled task created is corrupted and cannot be executed manually

**Comment by tal5ab** [comment]
Some more info just in case someone had the same issue
We found a diffrent 2012 AMI which does not have this issue , but we fail to identify what is diffrent 
And we also got the same behavior on a VirtualBox image of win 2012
So this is all about windows 2012 and not AWS\VB
