### ISSUE TITLE
You must specify an IP address when mapping to a non-VPC instance ? Fog::Compute::AWS::Error

### ISSUE THREAD

**Issue by sshilko** [mitchellh/vagrant-aws#435]
```
vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call': InvalidParameterCombination => You must specify an IP address when mapping to a non-VPC instance (Fog::Compute::AWS::Error)
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
	from /Users/sshilko/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/compute.rb:525:in `_request'
	from /Users/sshilko/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/compute.rb:520:in `request'
	from /Users/sshilko/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/requests/compute/associate_address.rb:42:in `associate_address'
	from /Users/sshilko/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:227:in `do_elastic_ip'
	from /Users/sshilko/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:151:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sshilko/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sshilko/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sshilko/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
any tips? i'm using 99% default configuration from puphpet
```
         provider:
             aws:
                 access_key_id: xxx
                 secret_access_key: yyy
                 keypair_name: vagrantkeypair
                 ami: ami-b82176d2
                 region: us-east-1
                 instance_type: m3.medium
                 security_groups:
                     - 'production something servers'
                 subnet_id: ''
                 elastic_ip: ''
                 iam_profile_name: 'namehere1'
                 elastic_ip: true
                 associate_public_ip: true
                 tags:
                     Source: Puphpet
```

**Comment by sshilko** [comment]
closing.. there seems to be some caching issues while changing config.yaml ruby does not immediattely recognize the changes
