### ISSUE TITLE
Cannot install plugin on Ubuntu 16.04 with vagrant 1.9.0

### ISSUE THREAD

**Issue by dsyer** [mitchellh/vagrant-aws#493]
I have a fresh install of Ubuntu 16.04, and I grabbed the latest vagrant (appears to be 1.9.0) from the install page. Can't install AWS plugin:

```
$ vagrant plugin install --verbose vagrant-aws
Installing the 'vagrant-aws' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'fog-xml' (>= 0) among 45 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/opt/vagrant/embedded/gems', execute `gem env` for more information
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:319:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `each'
...
```

**Comment by dsyer** [comment]
Also doesn't work with the vagrant package that comes with Ubuntu 16.04 (version 1.8.1):

```
$ vagrant plugin install --verbose vagrant-aws
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:173:in `block in verbose'
	from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
...
```

Am I doing something wrong here?

**Comment by weiserr** [comment]
I am having the same issue on Windows 10 using Vagrant 1.9.0 (vagrant_1.9.0.msi):

    C:\Users\row\Tools\Console2>vagrant plugin install vagrant-aws
    Installing the 'vagrant-aws' plugin. This can take a few minutes...
    C:/Users/row/Tools/Vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'fog-xml' (>= 0) among 45 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=C:/Users/row/Tools/Vagrant/embedded/gems', execute `gem env` for more information
            from C:/Users/row/Tools/Vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
            from C:/Users/row/Tools/Vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
            from C:/Users/row/Tools/Vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
            from C:/Users/row/Tools/Vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:319:in `block in activate_solution'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `each'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `activate_solution'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:244:in `internal_install'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:97:in `install'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in `call'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/action/install_gem.rb:37:in `call'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in `call'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `block in run'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in `busy'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `run'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/base.rb:14:in `action'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:32:in `block in execute'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `each'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `execute'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/root.rb:66:in `execute'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/cli.rb:42:in `execute'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/environment.rb:308:in `cli'
            from C:/Users/row/Tools/Vagrant/embedded/gems/gems/vagrant-1.9.0/bin/vagrant:123:in `<main>'

**Comment by ncdc** [comment]
It looks like ssl certificate verification is failing when the embedded gem binary tries to contact rubygems.org. I followed [this](https://gist.github.com/luislavena/f064211759ee0f806c88#gistcomment-1925425) and was able to get a new .pem file in place that fixed the verification failures, but I'm still not able to get it to install (it might be missing pkg-config or libiconv headers, or I don't have the path set up correctly)

**Comment by compuguy** [comment]
@dsyer I'm having this exact same issue on macOS sierra, with vagrant 1.9.0.

**Comment by jonatron** [comment]
While it's being fixed: https://releases.hashicorp.com/vagrant/1.8.7/

**Comment by compuguy** [comment]
You may want to install vagrant 1.8.6 instead. There are issues with 1.8.7.                                                                                                                                                                        Sent via the BlackBerry Hub for Android                                                                                                                                                                            From: notifications@github.comSent: December 1, 2016 8:58 AMTo: vagrant-aws@noreply.github.comReply-to: reply@reply.github.comCc: alex@compuguy1088.com; comment@noreply.github.comSubject: Re: [mitchellh/vagrant-aws] Cannot install plugin on Ubuntu 16.04 with vagrant 1.9.0 (#493)  While it's being fixed: https://releases.hashicorp.com/vagrant/1.8.7/

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mitchellh/vagrant-aws","title":"mitchellh/vagrant-aws","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mitchellh/vagrant-aws"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jonatron in #493: While it's being fixed: https://releases.hashicorp.com/vagrant/1.8.7/"}],"action":{"name":"View Issue","url":"https://github.com/mitchellh/vagrant-aws/issues/493#issuecomment-264179474"}}}

**Comment by riebling** [comment]
Having the same problem here. Very frustrating if you assume that getting the latest version will get you the best-working version
```
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'fog-xml' (>= 0) among 45 total gem(s) (Gem::LoadError)
```
Even when I put the fog-xml gem where Vagrant appears to be looking, it STILL can't find it. :-/

**Comment by ahawkins** [comment]
Confirmed broken on macOS sierra also.

**Comment by pjdurai** [comment]
Running into same problem here with Vagrant 1.9.0 in a Rhel 7.3.
Tried going back to Vagrant 1.8.7 and 1.8.6.  It still happens (fog-xml error) !
May be something permanently messed up in my attempts to get 1.9 working !?

**Comment by joebew42** [comment]
Confirm the same issue on ArchLinux, Vagrant 1.9.0

```
$ vagrant plugin install vagrant-aws
```

I get

```
 /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'fog-xml' (>= 0) among 44 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=/opt/vagrant/embedded/gems', execute `gem env` for more information
...
```

**Comment by sajfarahani** [comment]
Is there any solution here? I am having the same issue on 'CentOS Linux release 7.3.1611'.
