### ISSUE TITLE
Fog raising 'aws has no compute service' error on vagrant up.

### ISSUE THREAD

**Issue by treuherz** [mitchellh/vagrant-aws#505]
I can't get a Vagrant box to start up on AWS. Have tried with Vagrant 1.8.7 on Cygwin and Vagrant 1.9.1 on Ubuntu 16.04. Here's the error:
			  
```
$ vagrant up --provider=aws
/home/ubuntu/.vagrant.d/gems/2.2.5/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:18:in `rescue in new': aws has no compute service (Fog::Service::NotFound)
from /home/ubuntu/.vagrant.d/gems/2.2.5/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:8:in `new'
from /home/ubuntu/.vagrant.d/gems/2.2.5/gems/fog-core-1.43.0/lib/fog/compute.rb:54:in `new'
from /home/ubuntu/.vagrant.d/gems/2.2.5/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action/connect_aws.rb:40:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:182:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:182:in `block in action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
from /home/ubuntu/.vagrant.d/gems/2.2.5/gems/vagrant-aws-0.7.2/lib/vagrant-aws/provider.rb:32:in `state'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:506:in `state'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:145:in `initialize'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `new'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `machine'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:669:in `machine'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/command.rb:131:in `install_providers'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/command.rb:85:in `execute'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

and here is the Vagrantfile. The AMI is for Ubuntu 16.04 in eu-west-1.

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision :shell, :path => "provision/bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.provider "aws" do |aws, override|
    aws.access_key_id = "[redacted]"
    aws.secret_access_key = "[redacted]"
    aws.session_token = "[redacted]"
    aws.keypair_name = "[redacted]"

    aws.ami = "ami-e7eeb581"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/Downloads/key.pem"
  end
end
```

**Comment by mdrozdz17** [comment]
@treuherz did you ever get past this error? I am currently experiencing this same issue you had?

**Comment by treuherz** [comment]
Never did solve it, I'm afraid.
