### ISSUE TITLE
Vagrant 1.9.4 on Ubuntu 16.04 vagrant-share/helper/api (LoadError)

### ISSUE THREAD

**Issue by dpetukhov** [mitchellh/vagrant-aws#509]
Hello.

After installing vagrant_1.9.4_x86_64.deb on Ubuntu 16.04 with following commands:
`$ sudo dpkg -i vagrant_1.9.4_x86_64.deb`

I can't run vagrant. It shows me an error. Take a look:
```
dima@dmitry-774G:~/tmp$ vagrant 
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- vagrant-share/helper/api (LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share/activate.rb:244:in `<encoded>'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share/activate.rb:16:in `RGLoader_load'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share/activate.rb:16:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share.rb:23:in `block in <class:Plugin>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:75:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:75:in `block (2 levels) in help'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/registry.rb:49:in `block in each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/registry.rb:48:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/registry.rb:48:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:69:in `block in help'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/optparse.rb:917:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:57:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:57:in `help'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:32:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/bin/vagrant:127:in `<main>'
```
I fixed this by installing version 1.9.3 from here: https://releases.hashicorp.com/vagrant/1.9.3/
It works.

**Comment by benmwalt** [comment]
I got the same error when running the basic "vagrant" command following install of v1.9.4, however I was able to ignore it okay and follow the getting-started tutorial up to the point of "vagrant share":

``
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- vagrant-share/helper/api (LoadError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share/activate.rb:244:in `<encoded>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share/activate.rb:16:in `RGLoader_load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share/activate.rb:16:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.7/lib/vagrant-share.rb:29:in `block in <class:Plugin>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:36:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:36:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:308:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/bin/vagrant:127:in `<main>'
``

**Comment by benmwalt** [comment]
Oops - I put this comment in the wrong place - I'm using vagrant against VirtualBox on my Windows laptop. Ignore if irrelevant!

**Comment by fdawg4l** [comment]
https://github.com/mitchellh/vagrant/issues/8519#issuecomment-297413831

**Comment by sergeyklay** [comment]
The same on macOS Sierra with  Vagrant 1.9.4

**Comment by SergeyGusak** [comment]
Same problem

**Comment by delbekio** [comment]
same issue faced on mac Sierra with Vagrant 1.9.4

**Comment by ysying** [comment]
I have the same issue on Ubuntu 17.04.

**Comment by WestleyArgentum** [comment]
Same on OSX 10.12.4, Vagrant 1.9.4

**Comment by WestleyArgentum** [comment]
As @fdawg4l linked above, the solution is here: https://github.com/mitchellh/vagrant/issues/8519#issuecomment-297413831

**Comment by dpetukhov** [comment]
Yes, solution is:
> `$ vagrant plugin install vagrant-share --plugin-version 1.1.8`

**Comment by rnkhouse** [comment]
Temporary solution: Use version 1.9.3

**Comment by sillkongen** [comment]
@dpetukhov solution worked for me on El Capitan 10.11.6 and vagrant version 1.9.4

**Comment by Arbagen** [comment]
works for Debian GNU/Linux 8.7 (jessie)

**Comment by radishspirit88** [comment]
@dpetukhov solution worked for me on macOS Sierra 10.12.4

**Comment by verhulstm** [comment]
the problem also exists for vagrant v1.9.3

**Comment by sneaker-rohit** [comment]
Same problem on Kali Linux (Debian).

**Comment by klhurley** [comment]
Works, but why doesn't hashicorp fix this?

**Comment by verhulstm** [comment]
The recommendation of running:

$ vagrant plugin install vagrant-share --plugin-version 1.1.8

does not fix the problem on Ubuntu 16.04.2 LTS.

I fixed the issue on my workstation by completely uninstalling all of vagrant, then I deleted the hidden .vagrant.d dir (located in your home dir), then I reinstalled vagrant 1.9.4 and reinstalled all the vagrant plugins that I use.
