### ISSUE TITLE
URI must be ascii only "?gems=vagrant\u{2013}aws" (URI::InvalidURIError)

### ISSUE THREAD

**Issue by valugi** [mitchellh/vagrant-aws#517]
vagrant plugin install vagrant–aws
Installing the 'vagrant–aws' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge': URI must be ascii only "?gems=vagrant\u{2013}aws" (URI::InvalidURIError)
	from /opt/vagrant/embedded/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/api_set.rb:115:in `versions'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/api_set.rb:55:in `find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/composed_set.rb:55:in `block in find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/composed_set.rb:54:in `map'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/composed_set.rb:54:in `find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:31:in `find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:152:in `find_all'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/bundler.rb:460:in `find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/composed_set.rb:55:in `block in find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/composed_set.rb:54:in `map'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/composed_set.rb:54:in `find_all'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver.rb:204:in `find_possible'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver.rb:229:in `search_for'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:411:in `push_state_for_requirements'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:331:in `attempt_to_activate_existing_spec'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:318:in `attempt_to_activate'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:147:in `process_topmost_state'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:72:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/resolver.rb:191:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/request_set.rb:368:in `resolve'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/bundler.rb:303:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/bundler.rb:106:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/plugins/commands/plugin/action/install_gem.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.6/bin/vagrant:138:in `<main>'

**Comment by howdiz** [comment]
hitting a similar issue for vagrant-­vmware-­fusion were you able to get past it?
