### ISSUE TITLE
Exception when setting security_groups

### ISSUE THREAD

**Issue by filkry** [mitchellh/vagrant-aws#79]
I am setting security_groups with the following in my Vagrantfile:

``` ruby
config.vm.provider :aws do |aws, override|
    aws.access_key_id = <REDACTED>
    aws.secret_access_key = <REDACTED>
    aws.keypair_name = <REDACTED>

    aws.ami = "ami-7747d01e"
    aws.instance_type = 't1.micro'

    aws.security_groups = ['vagrant']

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = <REDACTED>
  end
```

I created the vagrant security group via the AWS web interface. I can connect without specifying a security group, but then my SSH command hangs.

Unfortunately, having the "aws.security_groups" line present causes a huge exception:

```
ERROR warden: Error occurred: Expected(200) <=> Actual(400 Bad Request)
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::AWS::Action::RunInstance:0x007f29c0899270>
 INFO machine: Calling action: read_state on provider AWS (new)
 INFO runner: Running action: #<Vagrant::Action::Builder:0x007f29c04fd4b8>
 INFO warden: Calling action: #<Vagrant::Action::Builtin::ConfigValidate:0x007f29c0502bc0>
 INFO warden: Calling action: #<VagrantPlugins::AWS::Action::ConnectAWS:0x007f29c0502b98>
 INFO connect_aws: Connecting to AWS...
 INFO warden: Calling action: #<VagrantPlugins::AWS::Action::ReadState:0x007f29c00dc0c8>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Expected(200) <=> Actual(400 Bad Request)
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000001249658>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000000177b4f0>
/home/fil/.vagrant.d/gems/gems/excon-0.22.1/lib/excon/middlewares/expects.rb:10:in `response_call': Expected(200) <=> Actual(400 Bad Request) (Excon::Errors::BadRequest)
    from /home/fil/.vagrant.d/gems/gems/excon-0.22.1/lib/excon/connection.rb:355:in `response'
    from /home/fil/.vagrant.d/gems/gems/excon-0.22.1/lib/excon/connection.rb:249:in `request'
    from /home/fil/.vagrant.d/gems/gems/fog-1.10.1/lib/fog/core/connection.rb:21:in `request'
    from /home/fil/.vagrant.d/gems/gems/fog-1.10.1/lib/fog/aws/compute.rb:384:in `_request'
    from /home/fil/.vagrant.d/gems/gems/fog-1.10.1/lib/fog/aws/compute.rb:379:in `request'
    from /home/fil/.vagrant.d/gems/gems/fog-1.10.1/lib/fog/aws/requests/compute/run_instances.rb:119:in `run_instances'
    from /home/fil/.vagrant.d/gems/gems/fog-1.10.1/lib/fog/aws/models/compute/server.rb:173:in `save'
    from /home/fil/.vagrant.d/gems/gems/fog-1.10.1/lib/fog/core/collection.rb:52:in `create'
    from /home/fil/.vagrant.d/gems/gems/vagrant-aws-0.2.2/lib/vagrant-aws/action/run_instance.rb:76:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/fil/.vagrant.d/gems/gems/vagrant-aws-0.2.2/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/fil/.vagrant.d/gems/gems/vagrant-aws-0.2.2/lib/vagrant-aws/action/sync_folders.rb:21:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/provision.rb:45:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/fil/.vagrant.d/gems/gems/vagrant-aws-0.2.2/lib/vagrant-aws/action/connect_aws.rb:41:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/machine.rb:147:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run
```

**Comment by fabianogoes** [comment]
I'm having the same problem, Has anyone managed to solve this problem?

`/Users/fabiano/.vagrant.d/gems/2.4.2/gems/excon-0.60.0/lib/excon/middlewares/expects.rb:7:in `response_call': The key pair 'vagrant' does not exist (Fog::Compute::AWS::NotFound)`

PS: I have already created the "key pair" in aws with the name "vagrant"
